// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm2ni_VBPYxyjEDj0021UZ4x9QRUJ0C2Q',
    appId: '1:921335909367:android:def5ccfcd6dffeffbf7cf2',
    messagingSenderId: '921335909367',
    projectId: 'cmov-project-b8486',
    databaseURL: 'https://cmov-project-b8486-default-rtdb.firebaseio.com',
    storageBucket: 'cmov-project-b8486.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP5XyIt5t0LRMotkrWGeRVm4GNxW5XAAY',
    appId: '1:921335909367:ios:29a00931597272f8bf7cf2',
    messagingSenderId: '921335909367',
    projectId: 'cmov-project-b8486',
    databaseURL: 'https://cmov-project-b8486-default-rtdb.firebaseio.com',
    storageBucket: 'cmov-project-b8486.appspot.com',
    iosClientId: '921335909367-sem7pkk9ehh7mig7m30c65st7msvo7jk.apps.googleusercontent.com',
    iosBundleId: 'com.example.facedetectionTestApp',
  );
}
